### ISSUE TITLE
SoC BGA pads have solder paste layer

### ISSUE THREAD

**Issue by hzeller** [jadonk/PocketBone#16]
The chip already has solder balls, this is why there typically shouldn't be solder paste on the pads to avoid shorting adjacent pins.

So I would suggest to edit the kicad_pcb file with

```
sed -i 's|\(pad [A-Z][0-9]* smd.*\)F.Paste |\1|g' pocketbone-kicad.kicad_pcb
```

to switch off the Paste layer on all BGA pins.

**Comment by pdp7** [comment]
@hzeller  Interesting.  So if there was a stencil for the PocketBone then it should not have any openings for the BGA?

**Comment by hzeller** [comment]
Indeed, no stencil holes for BGA pads.

If there should be something between the board and the BGA, it is flux in particular for hand-assembly.

Of course, I am just an amateur. I'd consult an assembly expert on this - maybe they suggest to put a tiny amount of solder paste on the center of the pad just to make use of the flux and the 'stickyness'. But not the same size of the pad, because that then would indeed overflow and create shorts due to double-solder amount.

**Comment by hzeller** [comment]
So @mwelling said that in an assembly typically there _is_ solder paste on the BGA pads. So disregard what I said.

**Comment by jadonk** [comment]
k. I'll note that Circuithub didn't have an issue with the kicad file as-is.
