### ISSUE TITLE
Consider migration to Altium or Kicad

### ISSUE THREAD

**Issue by jadonk** [jadonk/PocketBone#3]

**Comment by jadonk** [comment]
After discussing with others, definitely moving to Kicad. 

https://github.com/graycatlabs/OSD335x-KiCad

**Comment by o7-machinehum** [comment]
Are you making another repo or using this one?

**Comment by jadonk** [comment]
I'd like to keep using this repo, so I merged https://github.com/mwelling/pocketbone-kicad
